[[LibOSXUnwind]]
arch = "x86_64"
git-tree-sha1 = "fe58dbdcbbd0bec6b3f44c2b19c11b1c3084760e"
os = "macos"

    [[LibOSXUnwind.download]]
    sha256 = "a01c27600e4f128c80d390037c99de97fdd38043e0f13dd156cca7c1bb391ae5"
    url = "https://github.com/JuliaBinaryWrappers/LibOSXUnwind_jll.jl/releases/download/LibOSXUnwind-v0.0.6+2/LibOSXUnwind.v0.0.6.x86_64-apple-darwin.tar.gz"
