# Autogenerated wrapper script for LibOSXUnwind_jll for aarch64-apple-darwin
export libosxunwind

JLLWrappers.@generate_wrapper_header("LibOSXUnwind")
JLLWrappers.@declare_library_product(libosxunwind, "@rpath/libosxunwind.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libosxunwind,
        "lib/libosxunwind.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
